import React, { useState } from 'react';
import { Database, Copy, Check, Server, FileCode } from 'lucide-react';

const DatabaseView: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const sqlCode = `-- 1. پاکسازی کامل (حذف جداول قدیمی برای جلوگیری از تداخل)
DROP TABLE IF EXISTS medical_records CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS doctors CASCADE;
DROP TABLE IF EXISTS personnel CASCADE;

-- 2. جدول پرسنل (منشی، مدیر، پرستار)
create table personnel (
  national_code text primary key,
  first_name text not null,
  last_name text not null,
  role text not null, -- نقش: مدیر، منشی، پرستار
  password text not null default '123456',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. جدول پزشکان
create table doctors (
  doctor_id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  national_code text unique not null,
  specialty text not null,
  medical_system_number text not null,
  work_days text, -- مثال: شنبه,دوشنبه
  password text not null default '123456',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. جدول بیماران
create table patients (
  patient_id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  national_code text unique not null,
  birth_date text,
  phone_number text not null,
  gender text default 'Male',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. جدول داروها
create table medicines (
  medicine_id bigint generated by default as identity primary key,
  medicine_name text not null,
  dosage_medicine_name text, -- مثال: کپسول ۵۰۰
  dosage_count int default 1,
  consumption_time text,
  description text
);

-- 6. جدول نوبت‌ها
create table appointments (
  appointment_id bigint generated by default as identity primary key,
  tracking_code text unique not null,
  patient_id bigint references patients(patient_id) on delete cascade,
  doctor_id bigint references doctors(doctor_id) on delete cascade,
  reserved_date text not null,
  reserved_time text not null,
  status text default 'Pending', -- وضعیت: Pending, Completed, Canceled, NoShow
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. جدول سوابق پزشکی
create table medical_records (
  record_id bigint generated by default as identity primary key,
  patient_id bigint references patients(patient_id) on delete cascade,
  doctor_id bigint references doctors(doctor_id) on delete set null,
  medicine_id bigint references medicines(medicine_id) on delete set null,
  
  -- نکته مهم: این ستون کد ملی شخصی است که ثبت را انجام داده.
  -- چون ممکن است پزشک (جدول doctors) یا منشی (جدول personnel) باشد،
  -- اینجا Foreign Key نمی‌زنیم تا خطا ندهد.
  personnel_national_code text, 
  
  visit_date text not null,
  specialty text,
  chief_complaint text, -- شکایت اصلی بیمار
  description text,     -- تشخیص پزشک
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 8. داده‌های اولیه (Seed Data)

-- مدیر سیستم (نام کاربری: admin / رمز: 123456)
INSERT INTO personnel (national_code, first_name, last_name, role, password)
VALUES ('admin', 'مدیر', 'سیستم', 'مدیر', '123456');

-- یک پزشک نمونه (نام کاربری: 0011223344 / رمز: 123456)
INSERT INTO doctors (first_name, last_name, national_code, specialty, medical_system_number, work_days)
VALUES ('علی', 'رضایی', '0011223344', 'متخصص قلب و عروق', '12345', 'شنبه,دوشنبه,چهارشنبه');

-- یک بیمار نمونه
INSERT INTO patients (first_name, last_name, national_code, phone_number, gender, birth_date)
VALUES ('رضا', 'کاظمی', '1111111111', '09120000000', 'Male', '1370-01-01');

-- یک داروی نمونه
INSERT INTO medicines (medicine_name, dosage_medicine_name, consumption_time, description)
VALUES ('آموکسی‌سیلین', 'کپسول 500', 'هر ۸ ساعت', 'آنتی بیوتیک');

-- 9. تنظیمات امنیتی (باز کردن قفل جداول برای اپلیکیشن)
ALTER TABLE personnel DISABLE ROW LEVEL SECURITY;
ALTER TABLE doctors DISABLE ROW LEVEL SECURITY;
ALTER TABLE patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE medicines DISABLE ROW LEVEL SECURITY;
ALTER TABLE appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE medical_records DISABLE ROW LEVEL SECURITY;
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-mac-window pb-10">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-center gap-4 animate-item">
        <div>
           <h1 className="text-3xl font-bold text-stone-800 dark:text-stone-100 flex items-center gap-3 drop-shadow-sm">
             <div className="bg-stone-200/50 dark:bg-stone-800/50 p-2 rounded-xl text-stone-600 dark:text-stone-300 backdrop-blur-sm">
                <Database className="w-6 h-6" />
             </div>
             ساختار دیتابیس (SQL)
           </h1>
           <p className="text-stone-500 dark:text-stone-400 text-sm mt-1 font-medium">مشاهده کدهای ایجاد جداول و ارتباطات پایگاه داده</p>
        </div>

        <button 
            onClick={handleCopy}
            className="flex items-center gap-2 glass-card text-stone-600 dark:text-stone-300 px-5 py-3 rounded-xl hover:bg-stone-800 hover:text-white dark:hover:bg-stone-100 dark:hover:text-stone-900 transition-all font-bold text-sm shadow-sm active:scale-95"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'کپی شد' : 'کپی کدها'}
        </button>
      </div>

      {/* SQL View Panel */}
      <div className="glass-panel rounded-3xl overflow-hidden shadow-lg border border-stone-200/50 dark:border-white/10 animate-item" style={{animationDelay: '100ms'}}>
         {/* Terminal Header */}
         <div className="bg-[#1e1e1e] px-4 py-3 flex items-center justify-between border-b border-white/10">
            <div className="flex gap-2">
               <div className="w-3 h-3 rounded-full bg-red-500"></div>
               <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
               <div className="w-3 h-3 rounded-full bg-green-500"></div>
            </div>
            <div className="text-xs font-mono text-stone-400 flex items-center gap-2">
               <Server className="w-3 h-3" />
               schema.sql
            </div>
         </div>

         {/* Code Block */}
         <div className="relative bg-[#1e1e1e] p-6 overflow-x-auto custom-scrollbar" dir="ltr">
            <pre className="font-mono text-sm leading-6">
                <code className="language-sql" style={{ color: '#d4d4d4' }}>
                    {sqlCode.split('\n').map((line, i) => {
                        // Simple syntax highlighting simulation for visualization
                        const keywords = ['CREATE TABLE', 'DROP TABLE', 'IF EXISTS', 'PRIMARY KEY', 'VARCHAR', 'INT', 'BIGINT', 'NOT NULL', 'UNIQUE', 'DATE', 'TEXT', 'TIME', 'FOREIGN KEY', 'REFERENCES', 'AUTO_INCREMENT', 'TIMESTAMP', 'DEFAULT', 'INSERT INTO', 'VALUES', 'CASCADE', 'SET NULL', 'GENERATED BY DEFAULT AS IDENTITY', 'ALTER TABLE', 'DISABLE ROW LEVEL SECURITY'];
                        
                        return (
                            <div key={i} className="table-row">
                                <span className="table-cell select-none text-stone-600 text-right pr-4 w-8 border-r border-stone-800">{i + 1}</span>
                                <span className="table-cell pl-4 whitespace-pre">
                                    {line.trim().startsWith('--') ? (
                                        <span className="text-green-600 italic">{line}</span>
                                    ) : (
                                        line.split(' ').map((word, wIdx) => {
                                            const cleanWord = word.replace(/[,();]/g, '');
                                            const upperWord = cleanWord.toUpperCase();
                                            const isKeyword = keywords.includes(upperWord);
                                            const isType = ['INT', 'BIGINT', 'VARCHAR', 'DATE', 'TEXT', 'TIME', 'TIMESTAMP', 'BOOLEAN'].includes(upperWord);
                                            
                                            let color = '#d4d4d4'; // default
                                            if (isKeyword) color = '#569cd6'; // Blue
                                            if (isType) color = '#4ec9b0'; // Teal
                                            if (word.includes("'")) color = '#ce9178'; // String
                                            
                                            return <span key={wIdx} style={{ color }}>{word} </span>
                                        })
                                    )}
                                </span>
                            </div>
                        )
                    })}
                </code>
            </pre>
         </div>
      </div>
      
      {/* Schema Info Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 animate-item" style={{animationDelay: '200ms'}}>
         <div className="glass-card p-4 flex items-center gap-4">
            <div className="p-3 bg-blue-100/50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-300 rounded-xl">
               <FileCode className="w-6 h-6" />
            </div>
            <div>
               <div className="font-bold text-stone-800 dark:text-stone-100">۶ جدول اصلی</div>
               <div className="text-xs text-stone-500">جداول نرمال‌سازی شده</div>
            </div>
         </div>
         <div className="glass-card p-4 flex items-center gap-4">
            <div className="p-3 bg-purple-100/50 dark:bg-purple-900/30 text-purple-600 dark:text-purple-300 rounded-xl">
               <Server className="w-6 h-6" />
            </div>
            <div>
               <div className="font-bold text-stone-800 dark:text-stone-100">PostgreSQL</div>
               <div className="text-xs text-stone-500">سازگار با Supabase</div>
            </div>
         </div>
         <div className="glass-card p-4 flex items-center gap-4">
            <div className="p-3 bg-green-100/50 dark:bg-green-900/30 text-green-600 dark:text-green-300 rounded-xl">
               <Database className="w-6 h-6" />
            </div>
            <div>
               <div className="font-bold text-stone-800 dark:text-stone-100">ارتباطات (Relations)</div>
               <div className="text-xs text-stone-500">کلید خارجی و اصلی</div>
            </div>
         </div>
      </div>
    </div>
  );
};

export default DatabaseView;